markdown: kramdown
permalink: pretty
kramdown:
  input: GFM
  auto_ids: true
  extensions: ['smart', 'tables', 'with_toc_data', "highlight"]
paginate:     5
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: rouge
title : My A.I. journey
author :
  github : BrianPin
  twitter : BrianBin

production_url : http://brianpin.github.io
# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#
JB:
  analytics :
    provider : google
    gauges :
        site_id : 'SITE ID'
    google :
        tracking_id : 'UA-64339134-1'
    getclicky :
      site_id :
    mixpanel :
        token : '_MIXPANEL_TOKEN_'
    piwik :
        baseURL : 'myserver.tld/piwik' # Piwik installation address (without protocol)
        idsite : '1'                   # the id of the site on Piwik
linkedin_username:    brianpin
