markdown: kramdown
permalink: pretty
kramdown:
  input: GFM
  auto_ids: true
  extensions: ['smart', 'tables', 'with_toc_data', "highlight"]
paginate:     5
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: rouge
title : My A.I. journey
author :
  github : BrianPin
  twitter : BrianBin

production_url : http://brianpin.github.io
